name: Moje testy

on: [pull_request, push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Nastav Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Nainstaluj zavislosti
      run: |
        python -m pip install --upgrade pip
        python -m pip install unittest-xml-reporting coverage

    - name: Otestuj kod unittestem
      run: |
        coverage run -m unittest discover
        coverage report

    - name: Vygeneruj pokryti
      run: coverage xml

    - name: Nahraj vysledky pokryti
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report
        path: coverage.xml

    - name: Block PR if tests fail
      if: failure()
      run: exit 1
