name: Moje testy

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Nastav Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Nainstaluj zavislosti
      run: |
        python -m pip install --upgrade pip
        python -m pip install unittest-xml-reporting coverage

    - name: Otestuj kod unittestem
      run: |
        coverage run -m unittest discover
        coverage report

    - name: Otestuj pokryti
      run: coverage xml
      continue-on-error: true

    - name: Zkontroluj test pokryti
      uses: paambaati/codeclimate-action@v2.7.5
      with:
        coverageCommand: coverage xml

    - name: Block PR if tests fail
      if: failure()
      uses: actions/github-script@v6
      with:
        script: |
          github.issues.createComment({
            issue_number: context.issue.number,
            body: 'Testy selhaly. PR nelze sloučit, dokud neprojdou všechny testy.'
          })
